# Generated by Django 4.2.16 on 2024-11-06 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='is_registered',
        ),
        migrations.AddField(
            model_name='registration',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
