# Generated by Django 4.2.16 on 2025-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_branch_project_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(choices=[('DataScience', 'DataScience'), ('ML', 'ML'), ('GenAI', 'GenAI'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack'), ('AppDevelopment', 'AppDevelopment'), ('CyberSecurity', 'CyberSecurity'), ('CloudComputing', 'CloudComputing'), ('Networking', 'Networking'), ('IOT', 'IOT'), ('EmbeddedSystems', 'EmbeddedSystems'), ('Robotics', 'Robotics'), ('AI', 'AI'), ('AR/VR', 'AR/VR'), ('GameDevelopment', 'GameDevelopment'), ('QuantumComputing', 'QuantumComputing'), ('Blockchain', 'Blockchain'), ('DevOps', 'DevOps'), ('Testing', 'Testing'), ('Database', 'Database'), ('BigData', 'BigData'), ('WebDevelopment', 'WebDevelopment'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
